### Fonctions utilitaires

Compléter en ajoutant les fonctions de padding et de découpage en bloc.

In [50]:
from PIL import Image
import numpy as np
from math import log10, sqrt


def load(filename):
    """
    Charge une image à partir d'un fichier et la convertit en une matrice numpy.

    Args:
        filename (str): Le chemin du fichier de l'image à charger.

    Returns:
        ndarray: Matrice représentant l'image chargée.
    """
    toLoad = Image.open(filename)
    return np.array(toLoad)


def psnr(original, compressed):
    """
    Calcule le rapport signal sur bruit (PSNR) entre deux images.

    Args:
        original (ndarray): Matrice représentant l'image originale.
        compressed (ndarray): Matrice représentant l'image compressée.

    Returns:
        float: La valeur PSNR calculée.
    """
    mse = np.mean((original.astype(int) - compressed) ** 2)
    max_pixel = 255.0
    psnr = 20 * log10(max_pixel / sqrt(mse))
    return psnr


def save(matPix, filename):
    """
    Enregistre une matrice représentant une image dans un fichier.

    Args:
        matPix (ndarray): Matrice représentant l'image à enregistrer.
        filename (str): Le nom du fichier dans lequel enregistrer l'image.
    """
    Image.fromarray(matPix).save(filename)



def combler8bit(n):
    n_str = str(n)
    a_combler = 8 - len(n_str)
    nombre_comble = '0' * a_combler + n_str
    return str(nombre_comble)

### Utilitaires pour le calcul des palettes et des patchs

Fonctions auxiliaires pour manipuler les palettes, les pixels et les blocs. 

In [51]:
#question 1
def padding(matrice):
    """
    Ajoute du remplissage (padding) noir à une image pour garantir que ses dimensions soient des multiples de 4.

    Args:
        matrice (ndarray): Matrice représentant l'image à laquelle ajouter le padding.

    Returns:
        ndarray: Matrice de l'image avec padding.
    """
    # Récupérer les dimensions de l'image
    Hauteur = np.shape(matrice)[1]
    largeur = np.shape(matrice)[0]

    # Calculer le nombre de colonnes de padding nécessaires pour atteindre une dimension multiple de 4
    colonnes_supp_hauteur = (4 - Hauteur % 4) % 4
    colonnes_supp_largeur = (4 - largeur % 4) % 4

    # Créer une nouvelle matrice avec les dimensions ajustées et remplie de pixels noirs
    nouvelleMat = np.zeros((largeur + colonnes_supp_largeur, Hauteur + colonnes_supp_hauteur, 3), dtype=np.uint8)
    nouvelleMat[:largeur, :Hauteur] = matrice

    # Enregistrer l'image avec padding
    save(nouvelleMat, "procnoir.png")

    return nouvelleMat


#verification de la question 1 

def no_padding(matrice, largeur, hauteur):
    """
    Supprime le padding ajouté précédemment à une image, en fonction de ses dimensions d'origine.

    Args:
        matrice (ndarray): Matrice représentant l'image avec padding.
        largeur (int): Largeur originale de l'image avant le padding.
        hauteur (int): Hauteur originale de l'image avant le padding.

    Returns:
        ndarray: Matrice de l'image sans padding.
    """
    # Extraire la partie de l'image correspondant aux dimensions d'origine après le padding
    nouvellemat = matrice[:hauteur, :largeur]

    # Enregistrer l'image sans padding
    save(nouvellemat, "procsansnoir.png")

    
def verif_img_identique(image_originale, image_transformee):
    """
    Vérifie si deux images sont identiques.

    Args:
        image_originale (ndarray): Matrice représentant l'image d'origine.
        image_transformee (ndarray): Matrice représentant l'image transformée.

    Returns:
        bool: True si les deux images sont identiques, False sinon.
    """
    return np.array_equal(image_originale, image_transformee)


#Question 2 
def decouper_en_blocs(matrix):
    """
    Découpe une matrice en blocs 4x4 et les stocke dans une liste.
    
    Args:
        matrix (ndarray): Matrice à découper en blocs 4x4.
        
    Returns:
        list: Liste des blocs 4x4.
    """
    blocs = []  #bloc final
    
    # Récupérer les dimensions de la matrice
    hauteur, largeur, canaux = matrix.shape #canaux pour la couleur, en previsions
    
    # Parcourir la matrice en itérant sur les blocs de taille 4x4
    for i in range(0, hauteur, 4):
        for j in range(0, largeur, 4):
            # Extraire le bloc 4x4 à partir de la matrice
            bloc = matrix[i:i+4, j:j+4, :]
            blocs.append(bloc)  
            
    return blocs  

#Question 3
def reconstruire_image(blocs, img_originale):
    """
    Reconstruit une image à partir d'une liste de blocs 4x4.
    
    Args:
        blocs (list): Liste de blocs 4x4.
        img_originale (ndarray): Image originale à partir de laquelle les blocs ont été extraits.
        
    Returns:
        ndarray: Image reconstruite.
    """

    # Récupérer les dimensions de l'image originale
    hauteur, largeur, canaux = img_originale.shape
    
    # Créer une image vide avec les mêmes dimensions que l'image originale
    image_reconstruite = np.zeros((hauteur, largeur, canaux), dtype=np.uint8)
    
    index = 0  # Initialise l'indice pour accéder aux blocs
    # Parcourir l'image en itérant sur les blocs de taille 4x4
    for i in range(0, hauteur, 4):
        for j in range(0, largeur, 4):
            # Remplacer la section correspondante de l'image reconstruite par le bloc actuel
            image_reconstruite[i:i+4, j:j+4, :] = blocs[index]
            index += 1  # Passer au prochain bloc

    #save l'image reconstruite
    save(image_reconstruite, "imereconstruite.png")
    
    return image_reconstruite  


#Question 4
def tronque(n, p):
    """
    Enlève les p derniers bits de l'entier n.
    """
    n_str = str(n)
    return n_str[p:]


def generer_palette(couleur_a, couleur_b):
    """
    Crée la palette à partir des couleurs a et b.
    
    Args:
        couleur_a (numpy.ndarray): Couleur a.
        couleur_b (numpy.ndarray): Couleur b.
    
    Returns:
        numpy.ndarray: Palette de 4 couleurs.
    """
    # Palette de 4 couleurs avec les canaux rouge, vert et bleu

    palette = np.zeros((4, 3), dtype=np.uint8)
    
    palette[0] = couleur_a
    # Deuxième couleur de la palette : 2/3 de couleur a + 1/3 de couleur b
    palette[1] = np.round(2*couleur_a/3 +couleur_b/3)
    # Troisième couleur de la palette : 1/3 de couleur a + 2/3 de couleur b
    palette[2] = np.round(couleur_a/3 + 2*couleur_b/3)
    palette[3] = couleur_b
    
    return palette

#afficher palette : 
def afficher_palette(palette):
    """
    Affiche la palette comme une image.

    Args:
        palette (numpy.ndarray): Palette à afficher.
    """
    # Créer une image avec le mode RGB et les dimensions de la palette
    img_palette = Image.new("RGB", (palette.shape[0], 1))

    # Convertir la palette en liste de tuples (R, G, B)
    palette_liste = [tuple(couleur) for couleur in palette]

    # Définir les pixels de l'image avec les couleurs de la palette
    img_palette.putdata(palette_liste)

    # Afficher l'image
    img_palette.show()






### Les méthodes de choix des couleurs de la palette


On peut essayer plusieurs stratégies pour calculer les deux couleurs a et b:
* Calculer la couleur minimale et maximale
* Prendre des couleurs moyennes (calculer moyenne et variance pour trouver les meilleurs valeurs) 
* Calculer 10 valeurs au hasard et prendre la meilleure
* Partir d'un choix et perturber pour améliorer le résultat: on teste la meilleure modification de 16 d'un des canaux d'une des couleurs

In [52]:
def trouver_couleur_proche(pixel, palette):
    # Initialisation de la distance minimale à une valeur supérieure à la distance maximale possible
    distance_max = np.sqrt(255**2 + 255**2 + 255**2)
    distance_min = distance_max
    indice_couleur_proche = None
    
    for i in range(len(palette)):
        couleur_palette = palette[i]
        
        pixel_entier = pixel.astype(int)
        couleur_palette_entier = couleur_palette.astype(int)
        
        differences_carrees = (pixel_entier - couleur_palette_entier) ** 2
        
        somme_carrees = np.sum(differences_carrees)
        distance = np.sqrt(somme_carrees)
        
        # Instructions print pour le débogage
        
        print("Pixel:", pixel_entier)
        print("Couleur de la palette:", couleur_palette_entier)
        print("Différences au carré:", differences_carrees)
        print("Distance:", distance)
        print("---")
        
        if distance < distance_min:
            distance_min = distance
            indice_couleur_proche = i
    
    print("Indice de la couleur la plus proche:", indice_couleur_proche)
        
    return indice_couleur_proche


### Encodage d'un bloc

Écrire ici le code qui permet d'encoder un bloc et une palette en un entier.

In [53]:
def encoder_valeur_patch(couleur_a: np.ndarray, couleur_b: np.ndarray, liste_indices: list[int]) -> np.uint64:
    #init du patch
    patch = np.uint64(0)
    
    #indices de pixels
    for indice in range(len(liste_indices) - 1, -1, -1):
        # laisser de l'espace
        patch *= np.uint64(4)
        patch |= np.uint64(liste_indices[indice])
    
    #couleur b
    for i in range(2, -1, -1):
        # laisse de l'espace
        patch *= np.uint64(32) if i == 0 or i == 2 else np.uint64(64)
        patch |= np.uint64(couleur_b[i])
    
    #couleur a
    for i in range(2, -1, -1):
        # laisser de l'espace
        patch *= np.uint64(32) if i == 0 or i == 2 else np.uint64(64)
        patch |= np.uint64(couleur_a[i])
    
    return patch


### Écriture et lecture dans un fichier

### Fonctions de test

Écrire ici tous vos tests. Chaque fonction écrite doit être testée.

In [56]:
#section test question 1 : 
image_test = load("proc.jpg")#ne pas utiliser celle la directement, pas multiple de 4
padding(image_test) #question 1 

imgae_bord = load("procnoir.png")
no_padding(imgae_bord, image_test.shape[1], image_test.shape[0])

# on compare les deux images 
image_reduite = load("procsansnoir.png")
identique = verif_img_identique(image_test, image_reduite)

print(f"Image avec padding sauvegardée sous le nom 'procnoir.png'")
print(f"Image réduite sauvegardée sous le nom 'procsansnoir.png'\n")
print(f"Test question 1 fonctionne :  {identique}\n")

#section debug question 2 et 3 : 

#on décope l'image en bloc de 4
imgdecoup = decouper_en_blocs(imgae_bord)

#on la réassemble
imereconstruite = reconstruire_image(imgdecoup,imgae_bord)

print(f"Test question 2 et 3 image de base et image reconstruites sont les mêmes ?  :  {np.array_equal(imereconstruite, imgae_bord)}\n")



# section test question 4:

# Test de la fonction tronque
n = 255  # 11111111 en binaire (8 bits)
p = 3    # On veut enlever les 3 derniers bits

print(f"test question 4 tronque on tronc 255 de 3 bit, resultat attendu, 31(11111 en binaire) : {tronque(n, p)}\n")


# Test de la fonction generer_palette
couleur_a = np.array([255, 0, 0])  # Rouge
couleur_b = np.array([0, 0, 255])  # Bleu


#Test Question 4
print(f"test question 4 palette: \n ")
print("Palette obtenue :\n", generer_palette(couleur_a, couleur_b))
afficher_palette(generer_palette(couleur_a, couleur_b))  #debug



# Test de la question 5 : 

# palette de test
palette_test = generer_palette(couleur_a, couleur_b)
# pixel de test
pixel_test = np.array([50, 50, 51])  # Gris foncé

indice_couleur_proche = trouver_couleur_proche(pixel_test, palette_test)
print(indice_couleur_proche)
# Indice de la couleur de la palette la plus proche attendu pour le pixel de test
indice_couleur_attendu = 2  # Bleu, car le gris foncé est plus proche du bleu que des autes 

print(f"La question n°5 fonctionne correctement : {indice_couleur_proche == indice_couleur_attendu}")

# Test question n°6 : 

# Définition des valeurs de test pour couleur_a, couleur_b et liste_indices
couleur_a = np.array([255, 128, 64], dtype=np.uint8)
couleur_b = np.array([128, 64, 32], dtype=np.uint8)
palette=generer_palette(couleur_a, couleur_b)

# Appel de la fonction encoder_valeur_patch avec les valeurs de test
resultat_encodage = encoder_valeur_patch(couleur_a, couleur_b, palette[indice_couleur_proche])
print(f"l'encodage du patch de la questio 6 est : {resultat_encodage}")


Image avec padding sauvegardée sous le nom 'procnoir.png'
Image réduite sauvegardée sous le nom 'procsansnoir.png'

Test question 1 fonctionne :  True

Test question 2 et 3 image de base et image reconstruites sont les mêmes ?  :  True

test question 4 tronque on tronc 255 de 3 bit, resultat attendu, 31(11111 en binaire) : 

test question 4 palette: 
 
Palette obtenue :
 [[255   0   0]
 [170   0  85]
 [ 85   0 170]
 [  0   0 255]]
Pixel: [50 50 51]
Couleur de la palette: [255   0   0]
Différences au carré: [42025  2500  2601]
Distance: 217.08523671590382
---
Pixel: [50 50 51]
Couleur de la palette: [170   0  85]
Différences au carré: [14400  2500  1156]
Distance: 134.3726162579266
---
Pixel: [50 50 51]
Couleur de la palette: [ 85   0 170]
Différences au carré: [ 1225  2500 14161]
Distance: 133.7385509118444
---
Pixel: [50 50 51]
Couleur de la palette: [  0   0 255]
Différences au carré: [ 2500  2500 41616]
Distance: 215.90738755308954
---
Indice de la couleur la plus proche: 2
2
La que